name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare: Checkout Repository"
        uses: actions/checkout@v2
      - name: "Prepare: Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: v12.x

      - run: npm install
      - run: ng build --prod
      - run: ng lint
      # - run: npm run prettier
      # - run: npm run build
      # - run: npm run package
