name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Prepare: Checkout Repository"
        uses: actions/checkout@v2
      - name: "Prepare: Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: v18.x

      - run: npm install
      - run: npm run lint
      - run: npm run build --configuration=production

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: dist/wuza-web/*
